### ISSUE TITLE
Which dlls and where do I place them?

### ISSUE THREAD

**Issue by JAbelP** [pyrtlsdr/pyrtlsdr#136]
![image](https://user-images.githubusercontent.com/59974707/212522147-8b720508-1a9d-4f0f-a444-93ac603c29bb.png)
if I have a windows 10 64 bit machine and I am running pyrtlsdr in a venv where would I place the image? 
![image](https://user-images.githubusercontent.com/59974707/212522163-0bd26c82-9c15-4a62-a07a-3342c5f2c5c1.png)
I have been placing the dll in each folder and I still keep on getting the error ? 

(winning-the-radio-game) D:\Code\Python\radio>python listen_to_fm.py
Traceback (most recent call last):
  File "D:\Code\Python\radio\listen_to_fm.py", line 2, in <module>
    from rtlsdr import RtlSdr
  File "D:\Code\Python\radio\lib\site-packages\rtlsdr\__init__.py", line 56, in <module>
    from .librtlsdr import librtlsdr
  File "D:\Code\Python\radio\lib\site-packages\rtlsdr\librtlsdr.py", line 52, in <module>
    librtlsdr = load_librtlsdr()
  File "D:\Code\Python\radio\lib\site-packages\rtlsdr\librtlsdr.py", line 47, in load_librtlsdr
    raise ImportError('Error loading librtlsdr. Make sure librtlsdr '\
ImportError: Error loading librtlsdr. Make sure librtlsdr (and all of its dependencies) are in your path

**Comment by nocarryr** [comment]
@JAbelP  Check out the latest release (0.3.0).  Installation of `librtlsdr` can now be done via pip (instructions in the README)

Please drop a comment if it works or not.  I'd appreciate the feedback
