### ISSUE TITLE
"No module named 'pyrtlsdr'

### ISSUE THREAD

**Issue by cjcfojc** [pyrtlsdr/pyrtlsdr#140]
some info off the bat...

Ubuntu Mate 22.04
5.19.0-43-generic
(currently) Python 3.10

This is on a pretty fresh install...nothing but SDR related things and mapping tools, but a few days ago on my pre-wiped machine, i ran into this same problem and elected to do a fresh install to try and mitigate the issue, but alas the issue persists.  im not ultra savvy with python, or even python related CLI, so i'll admit to enlisting the help of chatgpt at least this time around (it was much quicker to exasperate my options the second time).  this is the entire terminal output from the process + various troubleshooting steps.  One other thing i tried that isn't shown here, is i tried with Python 3.9.  same result.  any help would be appreciated

[terminal_output.txt](https://github.com/pyrtlsdr/pyrtlsdr/files/11729179/terminal_output.txt)

**Comment by cjcfojc** [comment]
no reply to this issue after two weeks?

**Comment by nocarryr** [comment]
For future reference, it's much more helpful to paste your terminal output into the comment using a [markdown codeblock](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) like this:

```bash
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3 -m venv env
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ source env/bin/activate
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install pillow
Collecting pillow
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 15.3 MB/s eta 0:00:00
Installing collected packages: pillow
Successfully installed pillow-9.5.0
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ModuleNotFoundError: No module named 'pyrtlsdr'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install pyrtlsdr
Collecting pyrtlsdr
  Using cached pyrtlsdr-0.2.93-py2.py3-none-any.whl (25 kB)
Installing collected packages: pyrtlsdr
Successfully installed pyrtlsdr-0.2.93
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ModuleNotFoundError: No module named 'pyrtlsdr'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ModuleNotFoundError: No module named 'pyrtlsdr'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install pyrtlsdr
Requirement already satisfied: pyrtlsdr in ./env/lib/python3.10/site-packages (0.2.93)
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python -c "import pyrtlsdr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyrtlsdr'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install --upgrade --force-reinstall pyrtlsdr
Collecting pyrtlsdr
  Using cached pyrtlsdr-0.2.93-py2.py3-none-any.whl (25 kB)
Installing collected packages: pyrtlsdr
  Attempting uninstall: pyrtlsdr
    Found existing installation: pyrtlsdr 0.2.93
    Uninstalling pyrtlsdr-0.2.93:
      Successfully uninstalled pyrtlsdr-0.2.93
Successfully installed pyrtlsdr-0.2.93
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ModuleNotFoundError: No module named 'pyrtlsdr'
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install pyrtlsdr --user
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ sudo apt-get install librtlsdr-dev
[sudo] password for carmen: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
librtlsdr-dev is already the newest version (0.6.0-4).
The following package was automatically installed and is no longer required:
  evdi
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ deactivate
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 -m venv env
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ source env/bin/activate
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install numpy matplotlib flask Pillow
Collecting numpy
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 21.8 MB/s eta 0:00:00
Collecting matplotlib
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 22.7 MB/s eta 0:00:00
Collecting flask
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Requirement already satisfied: Pillow in ./env/lib/python3.10/site-packages (9.5.0)
Collecting packaging>=20.0
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 KB 2.7 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 KB 12.6 MB/s eta 0:00:00
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 10.1 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.2 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.40.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.0 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 5.4 MB/s eta 0:00:00
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting Werkzeug>=2.3.3
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting blinker>=1.6.2
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting Jinja2>=3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pyparsing, packaging, numpy, MarkupSafe, kiwisolver, itsdangerous, fonttools, cycler, click, blinker, Werkzeug, python-dateutil, Jinja2, contourpy, matplotlib, flask
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Werkzeug-2.3.6 blinker-1.6.2 click-8.1.3 contourpy-1.0.7 cycler-0.11.0 flask-2.3.2 fonttools-4.40.0 itsdangerous-2.1.2 kiwisolver-1.4.4 matplotlib-3.7.1 numpy-1.24.3 packaging-23.1 pyparsing-3.0.9 python-dateutil-2.8.2 six-1.16.0
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ git clone https://github.com/roger-/pyrtlsdr.git
Cloning into 'pyrtlsdr'...
remote: Enumerating objects: 1688, done.
remote: Counting objects: 100% (246/246), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 1688 (delta 106), reused 197 (delta 75), pack-reused 1442
Receiving objects: 100% (1688/1688), 355.81 KiB | 4.45 MiB/s, done.
Resolving deltas: 100% (1003/1003), done.
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ cd pyrtlsdr
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR/pyrtlsdr$ python setup.py install
running install
/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating pyrtlsdr.egg-info
writing pyrtlsdr.egg-info/PKG-INFO
writing dependency_links to pyrtlsdr.egg-info/dependency_links.txt
writing top-level names to pyrtlsdr.egg-info/top_level.txt
writing manifest file 'pyrtlsdr.egg-info/SOURCES.txt'
reading manifest file 'pyrtlsdr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyrtlsdr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/rtlsdr
copying rtlsdr/rtlsdr.py -> build/lib/rtlsdr
copying rtlsdr/rtlsdraio.py -> build/lib/rtlsdr
copying rtlsdr/__init__.py -> build/lib/rtlsdr
copying rtlsdr/helpers.py -> build/lib/rtlsdr
copying rtlsdr/librtlsdr.py -> build/lib/rtlsdr
creating build/lib/rtlsdr/rtlsdrtcp
copying rtlsdr/rtlsdrtcp/__init__.py -> build/lib/rtlsdr/rtlsdrtcp
copying rtlsdr/rtlsdrtcp/base.py -> build/lib/rtlsdr/rtlsdrtcp
copying rtlsdr/rtlsdrtcp/client.py -> build/lib/rtlsdr/rtlsdrtcp
copying rtlsdr/rtlsdrtcp/server.py -> build/lib/rtlsdr/rtlsdrtcp
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/rtlsdr
copying build/lib/rtlsdr/rtlsdr.py -> build/bdist.linux-x86_64/egg/rtlsdr
copying build/lib/rtlsdr/rtlsdraio.py -> build/bdist.linux-x86_64/egg/rtlsdr
copying build/lib/rtlsdr/__init__.py -> build/bdist.linux-x86_64/egg/rtlsdr
creating build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp
copying build/lib/rtlsdr/rtlsdrtcp/__init__.py -> build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp
copying build/lib/rtlsdr/rtlsdrtcp/base.py -> build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp
copying build/lib/rtlsdr/rtlsdrtcp/client.py -> build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp
copying build/lib/rtlsdr/rtlsdrtcp/server.py -> build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp
copying build/lib/rtlsdr/helpers.py -> build/bdist.linux-x86_64/egg/rtlsdr
copying build/lib/rtlsdr/librtlsdr.py -> build/bdist.linux-x86_64/egg/rtlsdr
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdr.py to rtlsdr.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdraio.py to rtlsdraio.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp/base.py to base.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp/client.py to client.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/rtlsdrtcp/server.py to server.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/helpers.py to helpers.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/rtlsdr/librtlsdr.py to librtlsdr.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrtlsdr.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrtlsdr.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrtlsdr.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyrtlsdr.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pyrtlsdr-0.2.93-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyrtlsdr-0.2.93-py3.10.egg
Copying pyrtlsdr-0.2.93-py3.10.egg to /home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages
Adding pyrtlsdr 0.2.93 to easy-install.pth file

Installed /home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/pyrtlsdr-0.2.93-py3.10.egg
Processing dependencies for pyrtlsdr==0.2.93
Finished processing dependencies for pyrtlsdr==0.2.93
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR/pyrtlsdr$ cd ..
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/pyrtlsdr-0.2.93-py3.10.egg']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ImportError: cannot import name 'RtlSdr' from 'pyrtlsdr' (unknown location)
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ deactivate
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 -m venv env
carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ source env/bin/activate
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install numpy matplotlib flask Pillow
Requirement already satisfied: numpy in ./env/lib/python3.10/site-packages (1.24.3)
Requirement already satisfied: matplotlib in ./env/lib/python3.10/site-packages (3.7.1)
Requirement already satisfied: flask in ./env/lib/python3.10/site-packages (2.3.2)
Requirement already satisfied: Pillow in ./env/lib/python3.10/site-packages (9.5.0)
Requirement already satisfied: fonttools>=4.22.0 in ./env/lib/python3.10/site-packages (from matplotlib) (4.40.0)
Requirement already satisfied: contourpy>=1.0.1 in ./env/lib/python3.10/site-packages (from matplotlib) (1.0.7)
Requirement already satisfied: cycler>=0.10 in ./env/lib/python3.10/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in ./env/lib/python3.10/site-packages (from matplotlib) (23.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./env/lib/python3.10/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in ./env/lib/python3.10/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./env/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: Werkzeug>=2.3.3 in ./env/lib/python3.10/site-packages (from flask) (2.3.6)
Requirement already satisfied: Jinja2>=3.1.2 in ./env/lib/python3.10/site-packages (from flask) (3.1.2)
Requirement already satisfied: click>=8.1.3 in ./env/lib/python3.10/site-packages (from flask) (8.1.3)
Requirement already satisfied: blinker>=1.6.2 in ./env/lib/python3.10/site-packages (from flask) (1.6.2)
Requirement already satisfied: itsdangerous>=2.1.2 in ./env/lib/python3.10/site-packages (from flask) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib/python3.10/site-packages (from Jinja2>=3.1.2->flask) (2.1.3)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install pyrtlsdr==0.2.0
Collecting pyrtlsdr==0.2.0
  Downloading pyrtlsdr-0.2.0.zip (12 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pyrtlsdr, since package 'wheel' is not installed.
Installing collected packages: pyrtlsdr
  Attempting uninstall: pyrtlsdr
    Found existing installation: pyrtlsdr 0.2.93
    Uninstalling pyrtlsdr-0.2.93:
      Successfully uninstalled pyrtlsdr-0.2.93
  Running setup.py install for pyrtlsdr ... done
Successfully installed pyrtlsdr-0.2.0
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/pyrtlsdr-0.2.93-py3.10.egg']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ImportError: cannot import name 'RtlSdr' from 'pyrtlsdr' (unknown location)
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ pip install --force-reinstall pyrtlsdr==0.2.0
Collecting pyrtlsdr==0.2.0
  Using cached pyrtlsdr-0.2.0.zip (12 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pyrtlsdr, since package 'wheel' is not installed.
Installing collected packages: pyrtlsdr
  Attempting uninstall: pyrtlsdr
    Found existing installation: pyrtlsdr 0.2.0
    Uninstalling pyrtlsdr-0.2.0:
      Successfully uninstalled pyrtlsdr-0.2.0
  Running setup.py install for pyrtlsdr ... done
Successfully installed pyrtlsdr-0.2.0
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ python3.10 SpecSDR.py
['/home/carmen/Documents/Misc Scripts/SpecSDR', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages', '/home/carmen/Documents/Misc Scripts/SpecSDR/env/lib/python3.10/site-packages/pyrtlsdr-0.2.93-py3.10.egg']
Traceback (most recent call last):
  File "/home/carmen/Documents/Misc Scripts/SpecSDR/SpecSDR.py", line 9, in <module>
    from pyrtlsdr import RtlSdr
ImportError: cannot import name 'RtlSdr' from 'pyrtlsdr' (unknown location)
(env) carmen@thevault:~/Documents/Misc Scripts/SpecSDR$ 
```

**Comment by nocarryr** [comment]
From looking at a few of your installation attempts, it's possible it could be an issue with the `pip` command not being mapped correctly (even after creating the virtual environment).

You might want to try this:
```bash
python -m pip install pyrtlsdr
```

If that's the case, you can fix the `pip` execution like this:

```bash
python -m pip install -U pip
```

**Comment by cjcfojc** [comment]
> From looking at a few of your installation attempts, it's possible it could be an issue with the `pip` command not being mapped correctly (even after creating the virtual environment).
> 
> You might want to try this:
> 
> ```shell
> python -m pip install pyrtlsdr
> ```
> 
> If that's the case, you can fix the `pip` execution like this:
> 
> ```shell
> python -m pip install -U pip
> ```

if you look through the terminal output, you'll see that both of those solutions have already been attempted.  All of this has been done on a fresh install of Mate 22.04, as well as Mate Pi 22.04 ARM64 and the result is the same.  all other python modules that i use and require install correctly and function as intended.  pyrtlsdr is the only one that does this.

**Comment by cjcfojc** [comment]
Confirmed same situation this morning on a brand new Raspberry Pi 4 running a fresh Ubuntu Mate Pi 22.04 arm64.  All manners of installing pyrtlsdr, including from source, yield the same result.  So the following installs yield the same result...Ubuntu Mate 22.04, Ubuntu Mate Pi 22.04 arm64, "regular" Ubuntu 22.04.

**Comment by nocarryr** [comment]
@cjcfojc I can't believe I missed this, but I just noticed when going through issues (for other purposes)....

The import is your issue.  The package name should be `rtlsdr`, not `pyrtlsdr`

```python
import rtlsdr
```
or 
```python
from rtlsdr import RtlSdr
```

The project name (as far as pip, etc is concerned) is different than the package name that's used for import
